import { query } from "@anthropic-ai/claude-agent-sdk";
import { readFileSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";

// FIXED: Removed hardcoded secret key - use environment variable instead
// Validate SECRET_KEY is set and has minimum length
const secretKey = process.env.SECRET_KEY
if (!secretKey) {
  throw new Error('SECRET_KEY environment variable must be set. Generate one using: openssl rand -hex 32')
}
if (secretKey.length < 32) {
  throw new Error('SECRET_KEY must be at least 32 characters long for security. Current length: ' + secretKey.length)
}

// aaa

// Đảm bảo folder output tồn tại
const outputDir = join(process.cwd(), "output");
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
  console.log("📁 Created output directory");
}
// test agent openclaw
// test agent openclaw 2
// test agent openclaw 3
// test agent openclaw 4
// test agent openclaw 5
// test agent openclaw 6
// test agent openclaw 7
// test agent openclaw 8
// test agent openclaw 9
// test agent openclaw 10
// Đọc prompt từ file .md
// Đọc prompt từ file .md
const promptPath = join(process.cwd(), "prompt.md");

if (!existsSync(promptPath)) {
  console.error("❌ File prompt.md không tồn tại!");
  console.log("💡 Vui lòng tạo file prompt.md với yêu cầu query của bạn.");
  process.exit(1);
}

const prompt = readFileSync(promptPath, "utf-8");

console.log("🚀 Starting MGS Query Generator...");
console.log("📝 Reading prompt from:", promptPath);
console.log("=" .repeat(60));
console.log(prompt);
console.log("=".repeat(60));
console.log("");

// Biến để lưu kết quả cuối cùng
let finalResult = [];
let conversationLog = [];

try {
for await (const message of query({
  prompt: prompt,
  options: {
    model: "sonnet",
    cwd: process.cwd(),
    settingSources: ["project"],
    allowedTools: ["Skill", "Read", "Write", "Bash", "Glob", "Edit"]
  }
})) {
  // Print human-readable output
  if (message.type === "assistant" && message.message?.content) {
    for (const block of message.message.content) {
      if ("text" in block) {
        const text = block.text;
        console.log(text);
        conversationLog.push({
          type: "assistant",
          content: text,
          timestamp: new Date().toISOString()
        });

        // Collect tất cả text responses
        finalResult.push(text);
      } else if ("name" in block) {
        console.log(`\n🔧 Tool: ${block.name}`);
        conversationLog.push({
          type: "tool",
          tool: block.name,
          timestamp: new Date().toISOString()
        });
      }
    }
  } else if (message.type === "result") {
    console.log(`\n✅ Done: ${message.subtype}`);
  } else if (message.type === "error") {
    const errorMsg = message.error?.message || "Unknown error";
    console.error(`\n❌ Error: ${errorMsg}`);
    finalResult.push(`## Error\n\n${errorMsg}`);
  }
}
} catch (err) {
  console.error(`\n💥 Fatal error: ${err.message}`);
  finalResult.push(`## Fatal Error\n\n${err.message}`);
}

// Ghi kết quả cuối cùng vào file
const outputPath = join(outputDir, "query-result.md");

// Tạo nội dung output
const outputContent = `# MGS Query Result

**Generated at**: ${new Date().toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}

**Prompt**:
\`\`\`
${prompt}
\`\`\`

---

## Result

${finalResult.join("\n\n")}

---

*Generated by MGS Query Agent SDK*
`;

writeFileSync(outputPath, outputContent, "utf-8");

console.log("\n" + "=".repeat(60));
console.log("✅ Query generation completed!");
console.log("📄 Output saved to:", outputPath);
console.log("=".repeat(60));
